### PR TITLE
add pre-commit config

### PR DESCRIPTION
**Pull request by Ohjeah**
Integrates https://pre-commit.com/

### CODE REVIEW

**Comment by kynan** [comment]
Can you elaborate what the use case is? `nbstripout` can be installed into your repository and then works as a clean/smudge filter.

What's the advantage of using a pre-commit hook instead? Note that this means the working copy of your notebooks will also get filtered.

**Comment by Ohjeah** [comment]
I am aware that you can install nbstripout manually as a git hook. Using the framework makes it more convenient imho, e.g. you can transfer the config file across projects, or you don't need to care about the venv which runs nbstripout.

**Comment by kynan** [comment]
My point is: `nbstripout` is normally used as a git *filter*, NOT a *pre-commit hook*.

The principle is fundamentally different:
* A [filter](https://git-scm.com/book/en/Customizing-Git-Git-Attributes) only modifies what git gets to see for committing or diffing. The working copy stays intact.
* A [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) is used to perform checks on a commit just before the snapshot is taken. It's only supposed to abort the commit if checks fails, not intended to modify the commit.

I see 2 issues with your proposal:
1. I think you're using a pre-commit hook in a way that's not intended. In fact when I tried your hook, the commit was aborted *because* files were modified. What was the behaviour you saw?
2. While there may be legit use cases why someone may want to use `nbstripout` to strip output on every commit in their working copy *and* the git snapshot, it needs to be clearly documented that this is a different mode of operation altogether. Otherwise it'll confuse users.

**Comment by lainiwa** [comment]
Although I did not know about git's filter,
I would note that `pre-commit` actually has certain hooks (created by the authors of `pre-commit` themselves), that modify the files (e.g. `trailing-whitespace` hook) and abort upon modification.
Therefore, I think, `pre-commit` **is** intended to be used that way.

Although, yes, this might not be the best way to organize one's workflow.

**Comment by Ohjeah** [comment]
Sorry for being unresponsive.

I am aware that the pre-commit functionality is slightly different., but I agree on documenting this difference.

I am also using code formatters like black or isort as pre-commit hooks, so the nbstripout is in line with that. Hooks modifying are intended to fail so that the user is forced to double check the results.

**Comment by kynan** [comment]
OK, I might revise my position and accept that there are different workflows that can be served by `nbstripout`. I'd like to see this workflow more thoroughly documented in this PR before merging.

**Comment by patricksheehan** [comment]
Any update here? Looking for similar functionality and would prefer not to have to roll my own since I use pre-commit elsewhere

**Comment by Ohjeah** [comment]
@kynan I merged our comments to document the pre-commit usage. Should be good to go now.

**Pull request merged**
