### PR TITLE
Ordered cell ids

### PR DESCRIPTION
**Pull request by JasonJoosteCSIRO**
This PR fixes a problem that I've been having with cell IDs not being consistent, even if the cell contents remain the same. It seems to have something to do with the new nbformat. Simply removing cell.id gives a warning which in future versions will be a hard exception. 

The solution that I have implemented that I think is most appropriate is to just add incremental cell id's (which is consistent with [the intended use of the ids](https://jupyter.org/enhancement-proposals/62-cell-id/cell-id.html#recommended-application-usage-of-id-field). Since IDs are usually randomly generated and most users aren't exposed to them I think this is a good solution. 

 I've added a new command line flag --keep-id to turn off this behaviour. My guess being on by default would match the expectations of most people. 

I've also added a couple of tests for this new format. 

Questions:
- I don't know anything about the zeppelin format and the IDs there seemed to be more meaningful. Right now it would also affect the zeppelin format, should I add a check and ignore zeppelin files?
- I haven't touched anything with bump2version or pypi because I'm not sure if this would justify a version change. Let me know what you'd like. 

This is my first time contributing to an open source project  like this and I'm not entirely sure about the etiquette in these situations. Let me know if I could do anything more!

Cheers,
Jason

### CODE REVIEW

**Review by kynan — CHANGES_REQUESTED** [review]
This mostly LGTM.

I'm not familiar with the Zeppelin notebook format (this was contributed by @ankitrokdeonsns ). However [their documentation](https://zeppelin.apache.org/docs/0.8.0/usage/rest_api/notebook.html) leads me to believe the IDs might be significant, so I suggest we don't change them.

My only remaining concern is that this is a behaviour change that might surprise some users. I'll release this as a new version.

**Comment by JasonJoosteCSIRO** [comment]
Should all be addressed right now. The merge in the middle is a little messy but I'm not sure its worth the wrangling. The zeppelin strip is in its own function so wasn't affected anyway.

**Comment by kynan** [comment]
Thanks for your contribution!

**Comment by JasonJoosteCSIRO** [comment]
My pleasure 🙂


Jason Jooste

Machine Learning Operations Engineer

Data61  |  CSIRO

***@***.******@***.***>

________________________________

**Pull request merged**
