### PR TITLE
Use argparse for argument parsing

### PR DESCRIPTION
**Pull request by kynan**
Currently nbstripout has a very hacked up way of argument parsing. I think we should switch to argparse. It would mean having to drop support for Python 2.6 (which Jupyter does not support anyway).

It would also mean that we can no longer use `install`, `uninstall` and `version` as commands and only support `--install`, `--uninstall`, `--version`. Currently we support both. Can you see any harm in this @michaelaye @mforbes?

### CODE REVIEW

**Comment by michaelaye** [comment]
i don't see any harm, but i think your last statement is incorrect, as argparse supports sub-commands, I think?

**Comment by kynan** [comment]
@michaelaye Yes, you're right, it could be done via subcommands. But I don't think it's worth the hassle and we can always add it when anyone complains. Merging this then.

**Comment by michaelaye** [comment]
you forgot to update the README accordingly.

**Comment by kynan** [comment]
@michaelaye I noticed that too. Done!

**Pull request merged**
